<?php
enum JsonCode: string {
    case USER_REGISTERED_SUCCESS = 'USER_REGISTERED_SUCCESS';
    case USER_LOGGED_SUCCESS = 'USER_LOGGED_SUCCESS';
    case AUTHENTICATED = 'AUTHENTICATED';
    case NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
    case EMPTY_NAME = 'EMPTY_NAME';
    case EMPTY_MAIL = 'EMPTY_MAIL';
    case EMPTY_PASS = 'EMPTY_PASS';
    case INVALID_MAIL_FORMAT = 'INVALID_MAIL_FORMAT';
    case BAD_CREDENTIALS = 'BAD_CREDENTIALS'; 
    case PASSWORD_LENGTH_ERROR = 'PASSWORD_LENGTH_ERROR';
    case ALREADY_EXISTS_EMAIL = 'ALREADY_EXISTS_EMAIL';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
}
